---
  - name: "Install aptitude using apt"
    apt: "name=aptitude state=latest update_cache=yes force_apt_get=yes"

  - name: "Install required system packages"
    apt: "name={{ item }} state=latest update_cache=yes"
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

  - name: "Install jsondiff using pip3"
    pip:
      name: jsondiff
      executable: pip3

  - name: "Add Docker GPG apt Key"
    apt_key:
      state: present
      url: "https://download.docker.com/linux/ubuntu/gpg"

  - name: "Add Docker Repository"
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
      state: present

  - name: "Update apt and install docker-ce"
    apt: "update_cache=yes name=docker-ce state=latest"

  - name: "Install Docker Module for Python"
    pip:
      name: docker

  - name: "Add operation user to 'docker' group"
    user:
      name: rarfaoui
      groups: sudo, docker